title: "Informe Práctica 6: Clases e interfaces genéricas. Principios SOLID"
author: alu0101346908
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
email: alu0101346908@ull.edu.es